print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
tip = int(input("How much tip would you like to give? 10, 12, or 15? "))
split_by = int(input("How many people to split the bill? "))
print(f"Each person should pay: ${round((bill/split_by)*(tip/100+1),2)}")